### ISSUE TITLE
Homebrew Installation Doesn't Work

### ISSUE THREAD

**Issue by mikaelacaron** [twostraws/Sitrep#30]
After installing via homebrew, then in a project directory that contains the .xcodeproj file running `sitrep` this gives 0 files scanned.
Do I need to create the .yml file? Or do anything else?

**Comment by twostraws** [comment]
Sorry for taking so long to reply to this! I have now investigated the issue and it seems likely to be caused by a version incompatibility with the underlying SwiftSyntax library we use. I've bumped the Swift version to 5.4 and added a clear error for when this happens, and hopefully that will help.

**Comment by mikaelacaron** [comment]
Looks that that was it! 👍 Thanks Paul!
